name: diff

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3.1.2
    
      - name: checkout to result branch
        run : git checkout -b result
         
      - name: cloning repository
        run : git clone https://github.com/devrel-kr/Web-Dev-For-Beginners.git
          
      - name: add upstream
        run : git remote add upstream https://github.com/microsoft/Web-Dev-For-Beginners.git

      
      - name: fetch upstream
        run : git fetch upstream

      - name: checkout to upstream
        run : git checkout upstream/main

      # git diff
      - name: Run diff.py
        run: python diff.py main upstream/main

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
            author_name: bmlsj
            author_email: gaga2353@gmail.com
            message: 'Your commit message'
            add: 'report_tree.md'
            push: origin micro