# This is a basic workflow to help you get started with Actions

name: auto-commit

on:
  push:
    branches: [ main ]

  workflow_dispatch:


jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Create report file
          run: date +%s > report.txt

        - name: Commit changes
          uses: EndBug/add-and-commit@v9
          with:
            author_name: bmlsj
            author_email: gaga2353@gmail.com
            message: 'Your commit message'
            add: 'report.txt'
