# This is a basic workflow to help you get started with Actions

name: build version check


on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  workflow_dispatch:


jobs:
  build:
    name: version check
    runs-on: ubuntu-latest

   
    steps:
      
      - uses: actions/checkout@v3

      - name: env build_version
        env:
          BUILD_VER : ${{github.run_number}}
        run: |
            echo "build version is $BUILD_VER"
            echo "${{ env.VERSION_BRANCH }}"
            echo "${{ env.VERSION_HASH_DATE }}"
        
      - name: Show variables
        run: |
          echo "${{ env.VERSION_HASH_DATE }} < VERSION_HASH_DATE"
          echo "${{ env.VERSION_HASH_ONLY }} < VERSION_HASH_ONLY"
          echo "${{ env.VERSION_CI }} < VERSION_CI"
          echo "${{ env.VERSION_BRANCH }} < VERSION_BRANCH"

