# This is a basic workflow to help you get started with Actions

name: build version check


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

   
    steps:
      
      - uses: actions/checkout@v3

      - name: env build_version
        env:
          BUILD_VER : ${{env.BUILD_NUMBER}}
        run: echo "build version is $BUILD_VER"

