
name: Compare

on:

#   schedule:
#     - cron : '0 0 * * 1'    # 매주 월요일 0시 0분에 실행

  push:
    branches: [ main ]
  #   paths:
  #     - "파일 경로"

  workflow_dispatch:
      

jobs:
  build:
    name : Compare
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      

      # set up python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      
    - name : "local commit id"
      env: 
        LOCAL_COMMIT_ID : $(git rev-parse main)        
      run: echo "Commit id => $LOCAL_COMMIT_ID"
  
    - name : remote
      run : |
            git remote add upstream https://github.com/Azure/azure-sdk-korean.git
            git remote -v

    - name : fetch
      run : git fetch upstream

    - name : checkout
      run : git checkout upstream/main


      # log 확인
    - name : git log
      run : git log


    - name : "upstream commit id"
      env: 
        UPSTREAM_COMMIT_ID : $(git rev-parse upstream/main)        
      run: echo "Commit id => $UPSTREAM_COMMIT_ID"



      # git diff    
    - name : git diff
      run: git diff COMMIT_ID UPSTREAM_COMMIT_ID