## https://github.com/ivanmilov/upstream_check_new_commits

name: Compare

on:

#   schedule:
#     - cron : '0 0 * * 1'    # 매주 월요일 0시 0분에 실행

#  push:
#  repository_dispatch:
#    types: [check_upstream]
  #   paths:
  #     - "파일 경로"

  workflow_dispatch:
      

jobs:
  build:
    name : check upstream
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      

      # set up python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}


      # log 확인
    - name : git log
      run : git log


    - name: Fetch upstream changes
      id: sync
      uses: ivanmilov/upstream_check_new_commits@v1
      with:
        upstream_repository: Azure/azure-sdk-korean
        upstream_branch: main
        target_branch: .


    - name : no new commits
      if: ${{ steps.sync.outputs.has_new_commits != 'true' }}
      run: echo "do not have new commits"


    - name: have new commits
      if: ${{ steps.sync.outputs.has_new_commits == 'true' }}
      uses: ivanmilov/telegram_notify_action@v1
      with:
        api_key: ${{secrets.TELEGRAM_API_KEY}}
        chat_id: ${{secrets.TELEGRAM_CHAT_ID}}
        message: "New commit in upstream repo ${{github.repository}}"
      

