name: Multi Tenant GAE Deploy
# 파일 이름 긁어오기
on:
  push:
  workflow_dispatch:

jobs:
  lookup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.filelist.outputs.file_names }}
    steps:
    - uses: actions/checkout@v2
    - name: Get all files
      id: filelist
      uses: the-coding-turtle/ga-file-list@v0.1
      with:
        directory: "."
        # file_extension: "txt"

  multi_tenant:
    needs: lookup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tenant: ${{fromJson(needs.lookup.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v2
    - name: Show all tenants
      id : list
      run: |
        touch file_list.txt
        echo "${{ matrix.TENANT }}" > file_list.txt
        echo ::set-output name=file_name::$(cat file_list.txt)

    - name : output tenants
      run : echo ${{ steps.list.outputs.file_name}}